name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - uses: actions/checkout@v3

      # 2) Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3) Install dependencies
      - run: npm ci

      # 4) Run ESLint (JS/TS)
      - run: npm run lint

      # 5) Run StyleLint (CSS)
      - run: npm run lint:style

      # 6) Check Prettier formatting (will fail if unformatted)
      - run: npx prettier --check .

      # 7) Build your Next.js app
      - run: npm run build
